-- Ensure media buckets exist for uploads (private buckets with RLS/signed/public-url policies)
INSERT INTO storage.buckets (id, name, public) VALUES
  ('product-images', 'product-images', false),
  ('seller-assets', 'seller-assets', false),
  ('requirement-attachments', 'requirement-attachments', false),
  ('media', 'media', false)
ON CONFLICT (id) DO UPDATE SET public = false;

-- IndiaMART-style category and subcategory seed data
WITH parent_seed(name, slug, description, icon, display_order) AS (
  VALUES
    ('Industrial Machinery', 'industrial-machinery', 'Verified suppliers for Industrial Machinery', 'Package', 1),
    ('Construction & Building Materials', 'construction-building-materials', 'Verified suppliers for Construction & Building Materials', 'Package', 2),
    ('Electrical Equipment', 'electrical-equipment', 'Verified suppliers for Electrical Equipment', 'Package', 3),
    ('Electronics & Components', 'electronics-components', 'Verified suppliers for Electronics & Components', 'Package', 4),
    ('Chemicals & Solvents', 'chemicals-solvents', 'Verified suppliers for Chemicals & Solvents', 'Package', 5),
    ('Textiles, Yarn & Fabrics', 'textiles-yarn-fabrics', 'Verified suppliers for Textiles, Yarn & Fabrics', 'Package', 6),
    ('Apparel & Fashion', 'apparel-fashion', 'Verified suppliers for Apparel & Fashion', 'Package', 7),
    ('Food & Beverages', 'food-beverages', 'Verified suppliers for Food & Beverages', 'Package', 8),
    ('Agriculture & Farming', 'agriculture-farming', 'Verified suppliers for Agriculture & Farming', 'Package', 9),
    ('Packaging Materials', 'packaging-materials', 'Verified suppliers for Packaging Materials', 'Package', 10),
    ('Automobile Parts', 'automobile-parts', 'Verified suppliers for Automobile Parts', 'Package', 11),
    ('Medical & Healthcare', 'medical-healthcare', 'Verified suppliers for Medical & Healthcare', 'Package', 12),
    ('Metals & Alloys', 'metals-alloys', 'Verified suppliers for Metals & Alloys', 'Package', 13),
    ('Plastic & Rubber Products', 'plastic-rubber-products', 'Verified suppliers for Plastic & Rubber Products', 'Package', 14),
    ('Office & School Supplies', 'office-school-supplies', 'Verified suppliers for Office & School Supplies', 'Package', 15),
    ('Furniture & Home Decor', 'furniture-home-decor', 'Verified suppliers for Furniture & Home Decor', 'Package', 16),
    ('Safety & Security', 'safety-security', 'Verified suppliers for Safety & Security', 'Package', 17),
    ('Logistics & Material Handling', 'logistics-material-handling', 'Verified suppliers for Logistics & Material Handling', 'Package', 18),
    ('IT & Software Services', 'it-software-services', 'Verified suppliers for IT & Software Services', 'Package', 19),
    ('Printing & Advertising', 'printing-advertising', 'Verified suppliers for Printing & Advertising', 'Package', 20)
), upsert_parents AS (
  INSERT INTO public.categories (name, slug, description, icon, level, is_active, display_order, sort_order)
  SELECT name, slug, description, icon, 1, true, display_order, display_order FROM parent_seed
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = COALESCE(public.categories.description, EXCLUDED.description),
    icon = COALESCE(public.categories.icon, EXCLUDED.icon),
    level = 1,
    is_active = true,
    display_order = EXCLUDED.display_order,
    sort_order = EXCLUDED.sort_order,
    updated_at = now()
  RETURNING id, slug
), child_seed(parent_slug, name, slug, description, display_order) AS (
  VALUES
    ('industrial-machinery', 'CNC Machines', 'industrial-machinery-cnc-machines', 'Bulk CNC Machines manufacturers, wholesalers and suppliers', 1),
    ('industrial-machinery', 'Lathe Machines', 'industrial-machinery-lathe-machines', 'Bulk Lathe Machines manufacturers, wholesalers and suppliers', 2),
    ('industrial-machinery', 'Packaging Machines', 'industrial-machinery-packaging-machines', 'Bulk Packaging Machines manufacturers, wholesalers and suppliers', 3),
    ('industrial-machinery', 'Textile Machinery', 'industrial-machinery-textile-machinery', 'Bulk Textile Machinery manufacturers, wholesalers and suppliers', 4),
    ('industrial-machinery', 'Food Processing Machines', 'industrial-machinery-food-processing-machines', 'Bulk Food Processing Machines manufacturers, wholesalers and suppliers', 5),
    ('industrial-machinery', 'Printing Machines', 'industrial-machinery-printing-machines', 'Bulk Printing Machines manufacturers, wholesalers and suppliers', 6),
    ('industrial-machinery', 'Pharmaceutical Machinery', 'industrial-machinery-pharmaceutical-machinery', 'Bulk Pharmaceutical Machinery manufacturers, wholesalers and suppliers', 7),
    ('industrial-machinery', 'Hydraulic Press', 'industrial-machinery-hydraulic-press', 'Bulk Hydraulic Press manufacturers, wholesalers and suppliers', 8),
    ('industrial-machinery', 'Air Compressors', 'industrial-machinery-air-compressors', 'Bulk Air Compressors manufacturers, wholesalers and suppliers', 9),
    ('industrial-machinery', 'Industrial Boilers', 'industrial-machinery-industrial-boilers', 'Bulk Industrial Boilers manufacturers, wholesalers and suppliers', 10),
    ('construction-building-materials', 'Cement', 'construction-building-materials-cement', 'Bulk Cement manufacturers, wholesalers and suppliers', 1),
    ('construction-building-materials', 'TMT Bars', 'construction-building-materials-tmt-bars', 'Bulk TMT Bars manufacturers, wholesalers and suppliers', 2),
    ('construction-building-materials', 'Bricks', 'construction-building-materials-bricks', 'Bulk Bricks manufacturers, wholesalers and suppliers', 3),
    ('construction-building-materials', 'Tiles', 'construction-building-materials-tiles', 'Bulk Tiles manufacturers, wholesalers and suppliers', 4),
    ('construction-building-materials', 'Plywood', 'construction-building-materials-plywood', 'Bulk Plywood manufacturers, wholesalers and suppliers', 5),
    ('construction-building-materials', 'Sanitary Ware', 'construction-building-materials-sanitary-ware', 'Bulk Sanitary Ware manufacturers, wholesalers and suppliers', 6),
    ('construction-building-materials', 'Paints', 'construction-building-materials-paints', 'Bulk Paints manufacturers, wholesalers and suppliers', 7),
    ('construction-building-materials', 'PVC Pipes', 'construction-building-materials-pvc-pipes', 'Bulk PVC Pipes manufacturers, wholesalers and suppliers', 8),
    ('construction-building-materials', 'Scaffolding', 'construction-building-materials-scaffolding', 'Bulk Scaffolding manufacturers, wholesalers and suppliers', 9),
    ('construction-building-materials', 'Ready Mix Concrete', 'construction-building-materials-ready-mix-concrete', 'Bulk Ready Mix Concrete manufacturers, wholesalers and suppliers', 10),
    ('electrical-equipment', 'Switchgear', 'electrical-equipment-switchgear', 'Bulk Switchgear manufacturers, wholesalers and suppliers', 1),
    ('electrical-equipment', 'Transformers', 'electrical-equipment-transformers', 'Bulk Transformers manufacturers, wholesalers and suppliers', 2),
    ('electrical-equipment', 'Wires & Cables', 'electrical-equipment-wires-cables', 'Bulk Wires & Cables manufacturers, wholesalers and suppliers', 3),
    ('electrical-equipment', 'LED Lights', 'electrical-equipment-led-lights', 'Bulk LED Lights manufacturers, wholesalers and suppliers', 4),
    ('electrical-equipment', 'Solar Panels', 'electrical-equipment-solar-panels', 'Bulk Solar Panels manufacturers, wholesalers and suppliers', 5),
    ('electrical-equipment', 'Inverters', 'electrical-equipment-inverters', 'Bulk Inverters manufacturers, wholesalers and suppliers', 6),
    ('electrical-equipment', 'Motors', 'electrical-equipment-motors', 'Bulk Motors manufacturers, wholesalers and suppliers', 7),
    ('electrical-equipment', 'Control Panels', 'electrical-equipment-control-panels', 'Bulk Control Panels manufacturers, wholesalers and suppliers', 8),
    ('electrical-equipment', 'Circuit Breakers', 'electrical-equipment-circuit-breakers', 'Bulk Circuit Breakers manufacturers, wholesalers and suppliers', 9),
    ('electrical-equipment', 'Batteries', 'electrical-equipment-batteries', 'Bulk Batteries manufacturers, wholesalers and suppliers', 10),
    ('electronics-components', 'PCB', 'electronics-components-pcb', 'Bulk PCB manufacturers, wholesalers and suppliers', 1),
    ('electronics-components', 'Sensors', 'electronics-components-sensors', 'Bulk Sensors manufacturers, wholesalers and suppliers', 2),
    ('electronics-components', 'Semiconductors', 'electronics-components-semiconductors', 'Bulk Semiconductors manufacturers, wholesalers and suppliers', 3),
    ('electronics-components', 'Connectors', 'electronics-components-connectors', 'Bulk Connectors manufacturers, wholesalers and suppliers', 4),
    ('electronics-components', 'CCTV Cameras', 'electronics-components-cctv-cameras', 'Bulk CCTV Cameras manufacturers, wholesalers and suppliers', 5),
    ('electronics-components', 'Consumer Electronics', 'electronics-components-consumer-electronics', 'Bulk Consumer Electronics manufacturers, wholesalers and suppliers', 6),
    ('electronics-components', 'Mobile Accessories', 'electronics-components-mobile-accessories', 'Bulk Mobile Accessories manufacturers, wholesalers and suppliers', 7),
    ('electronics-components', 'Power Supplies', 'electronics-components-power-supplies', 'Bulk Power Supplies manufacturers, wholesalers and suppliers', 8),
    ('electronics-components', 'Electronic Displays', 'electronics-components-electronic-displays', 'Bulk Electronic Displays manufacturers, wholesalers and suppliers', 9),
    ('electronics-components', 'Automation Components', 'electronics-components-automation-components', 'Bulk Automation Components manufacturers, wholesalers and suppliers', 10),
    ('chemicals-solvents', 'Industrial Chemicals', 'chemicals-solvents-industrial-chemicals', 'Bulk Industrial Chemicals manufacturers, wholesalers and suppliers', 1),
    ('chemicals-solvents', 'Specialty Chemicals', 'chemicals-solvents-specialty-chemicals', 'Bulk Specialty Chemicals manufacturers, wholesalers and suppliers', 2),
    ('chemicals-solvents', 'Paint Chemicals', 'chemicals-solvents-paint-chemicals', 'Bulk Paint Chemicals manufacturers, wholesalers and suppliers', 3),
    ('chemicals-solvents', 'Water Treatment Chemicals', 'chemicals-solvents-water-treatment-chemicals', 'Bulk Water Treatment Chemicals manufacturers, wholesalers and suppliers', 4),
    ('chemicals-solvents', 'Laboratory Chemicals', 'chemicals-solvents-laboratory-chemicals', 'Bulk Laboratory Chemicals manufacturers, wholesalers and suppliers', 5),
    ('chemicals-solvents', 'Adhesives', 'chemicals-solvents-adhesives', 'Bulk Adhesives manufacturers, wholesalers and suppliers', 6),
    ('chemicals-solvents', 'Resins', 'chemicals-solvents-resins', 'Bulk Resins manufacturers, wholesalers and suppliers', 7),
    ('chemicals-solvents', 'Solvents', 'chemicals-solvents-solvents', 'Bulk Solvents manufacturers, wholesalers and suppliers', 8),
    ('chemicals-solvents', 'Agro Chemicals', 'chemicals-solvents-agro-chemicals', 'Bulk Agro Chemicals manufacturers, wholesalers and suppliers', 9),
    ('chemicals-solvents', 'Cleaning Chemicals', 'chemicals-solvents-cleaning-chemicals', 'Bulk Cleaning Chemicals manufacturers, wholesalers and suppliers', 10),
    ('textiles-yarn-fabrics', 'Cotton Fabric', 'textiles-yarn-fabrics-cotton-fabric', 'Bulk Cotton Fabric manufacturers, wholesalers and suppliers', 1),
    ('textiles-yarn-fabrics', 'Polyester Fabric', 'textiles-yarn-fabrics-polyester-fabric', 'Bulk Polyester Fabric manufacturers, wholesalers and suppliers', 2),
    ('textiles-yarn-fabrics', 'Denim', 'textiles-yarn-fabrics-denim', 'Bulk Denim manufacturers, wholesalers and suppliers', 3),
    ('textiles-yarn-fabrics', 'Knitted Fabric', 'textiles-yarn-fabrics-knitted-fabric', 'Bulk Knitted Fabric manufacturers, wholesalers and suppliers', 4),
    ('textiles-yarn-fabrics', 'Silk Fabric', 'textiles-yarn-fabrics-silk-fabric', 'Bulk Silk Fabric manufacturers, wholesalers and suppliers', 5),
    ('textiles-yarn-fabrics', 'Yarn', 'textiles-yarn-fabrics-yarn', 'Bulk Yarn manufacturers, wholesalers and suppliers', 6),
    ('textiles-yarn-fabrics', 'Garment Accessories', 'textiles-yarn-fabrics-garment-accessories', 'Bulk Garment Accessories manufacturers, wholesalers and suppliers', 7),
    ('textiles-yarn-fabrics', 'Home Furnishing Fabric', 'textiles-yarn-fabrics-home-furnishing-fabric', 'Bulk Home Furnishing Fabric manufacturers, wholesalers and suppliers', 8),
    ('textiles-yarn-fabrics', 'Non Woven Fabric', 'textiles-yarn-fabrics-non-woven-fabric', 'Bulk Non Woven Fabric manufacturers, wholesalers and suppliers', 9),
    ('textiles-yarn-fabrics', 'Technical Textiles', 'textiles-yarn-fabrics-technical-textiles', 'Bulk Technical Textiles manufacturers, wholesalers and suppliers', 10),
    ('apparel-fashion', 'T-Shirts', 'apparel-fashion-t-shirts', 'Bulk T-Shirts manufacturers, wholesalers and suppliers', 1),
    ('apparel-fashion', 'Shirts', 'apparel-fashion-shirts', 'Bulk Shirts manufacturers, wholesalers and suppliers', 2),
    ('apparel-fashion', 'Uniforms', 'apparel-fashion-uniforms', 'Bulk Uniforms manufacturers, wholesalers and suppliers', 3),
    ('apparel-fashion', 'Ethnic Wear', 'apparel-fashion-ethnic-wear', 'Bulk Ethnic Wear manufacturers, wholesalers and suppliers', 4),
    ('apparel-fashion', 'Sportswear', 'apparel-fashion-sportswear', 'Bulk Sportswear manufacturers, wholesalers and suppliers', 5),
    ('apparel-fashion', 'Kids Wear', 'apparel-fashion-kids-wear', 'Bulk Kids Wear manufacturers, wholesalers and suppliers', 6),
    ('apparel-fashion', 'Women Wear', 'apparel-fashion-women-wear', 'Bulk Women Wear manufacturers, wholesalers and suppliers', 7),
    ('apparel-fashion', 'Winter Wear', 'apparel-fashion-winter-wear', 'Bulk Winter Wear manufacturers, wholesalers and suppliers', 8),
    ('apparel-fashion', 'Workwear', 'apparel-fashion-workwear', 'Bulk Workwear manufacturers, wholesalers and suppliers', 9),
    ('apparel-fashion', 'Footwear', 'apparel-fashion-footwear', 'Bulk Footwear manufacturers, wholesalers and suppliers', 10),
    ('food-beverages', 'Rice', 'food-beverages-rice', 'Bulk Rice manufacturers, wholesalers and suppliers', 1),
    ('food-beverages', 'Wheat', 'food-beverages-wheat', 'Bulk Wheat manufacturers, wholesalers and suppliers', 2),
    ('food-beverages', 'Pulses', 'food-beverages-pulses', 'Bulk Pulses manufacturers, wholesalers and suppliers', 3),
    ('food-beverages', 'Spices', 'food-beverages-spices', 'Bulk Spices manufacturers, wholesalers and suppliers', 4),
    ('food-beverages', 'Edible Oil', 'food-beverages-edible-oil', 'Bulk Edible Oil manufacturers, wholesalers and suppliers', 5),
    ('food-beverages', 'Dry Fruits', 'food-beverages-dry-fruits', 'Bulk Dry Fruits manufacturers, wholesalers and suppliers', 6),
    ('food-beverages', 'Tea & Coffee', 'food-beverages-tea-coffee', 'Bulk Tea & Coffee manufacturers, wholesalers and suppliers', 7),
    ('food-beverages', 'Dairy Products', 'food-beverages-dairy-products', 'Bulk Dairy Products manufacturers, wholesalers and suppliers', 8),
    ('food-beverages', 'Snacks', 'food-beverages-snacks', 'Bulk Snacks manufacturers, wholesalers and suppliers', 9),
    ('food-beverages', 'Beverages', 'food-beverages-beverages', 'Bulk Beverages manufacturers, wholesalers and suppliers', 10),
    ('agriculture-farming', 'Seeds', 'agriculture-farming-seeds', 'Bulk Seeds manufacturers, wholesalers and suppliers', 1),
    ('agriculture-farming', 'Fertilizers', 'agriculture-farming-fertilizers', 'Bulk Fertilizers manufacturers, wholesalers and suppliers', 2),
    ('agriculture-farming', 'Farm Machinery', 'agriculture-farming-farm-machinery', 'Bulk Farm Machinery manufacturers, wholesalers and suppliers', 3),
    ('agriculture-farming', 'Irrigation Systems', 'agriculture-farming-irrigation-systems', 'Bulk Irrigation Systems manufacturers, wholesalers and suppliers', 4),
    ('agriculture-farming', 'Greenhouse Supplies', 'agriculture-farming-greenhouse-supplies', 'Bulk Greenhouse Supplies manufacturers, wholesalers and suppliers', 5),
    ('agriculture-farming', 'Animal Feed', 'agriculture-farming-animal-feed', 'Bulk Animal Feed manufacturers, wholesalers and suppliers', 6),
    ('agriculture-farming', 'Pesticides', 'agriculture-farming-pesticides', 'Bulk Pesticides manufacturers, wholesalers and suppliers', 7),
    ('agriculture-farming', 'Agricultural Tools', 'agriculture-farming-agricultural-tools', 'Bulk Agricultural Tools manufacturers, wholesalers and suppliers', 8),
    ('agriculture-farming', 'Organic Farming', 'agriculture-farming-organic-farming', 'Bulk Organic Farming manufacturers, wholesalers and suppliers', 9),
    ('agriculture-farming', 'Tractors', 'agriculture-farming-tractors', 'Bulk Tractors manufacturers, wholesalers and suppliers', 10),
    ('packaging-materials', 'Corrugated Boxes', 'packaging-materials-corrugated-boxes', 'Bulk Corrugated Boxes manufacturers, wholesalers and suppliers', 1),
    ('packaging-materials', 'Plastic Packaging', 'packaging-materials-plastic-packaging', 'Bulk Plastic Packaging manufacturers, wholesalers and suppliers', 2),
    ('packaging-materials', 'Paper Bags', 'packaging-materials-paper-bags', 'Bulk Paper Bags manufacturers, wholesalers and suppliers', 3),
    ('packaging-materials', 'Labels', 'packaging-materials-labels', 'Bulk Labels manufacturers, wholesalers and suppliers', 4),
    ('packaging-materials', 'Flexible Packaging', 'packaging-materials-flexible-packaging', 'Bulk Flexible Packaging manufacturers, wholesalers and suppliers', 5),
    ('packaging-materials', 'Wooden Pallets', 'packaging-materials-wooden-pallets', 'Bulk Wooden Pallets manufacturers, wholesalers and suppliers', 6),
    ('packaging-materials', 'Packaging Films', 'packaging-materials-packaging-films', 'Bulk Packaging Films manufacturers, wholesalers and suppliers', 7),
    ('packaging-materials', 'Bottles & Jars', 'packaging-materials-bottles-jars', 'Bulk Bottles & Jars manufacturers, wholesalers and suppliers', 8),
    ('packaging-materials', 'Strapping Rolls', 'packaging-materials-strapping-rolls', 'Bulk Strapping Rolls manufacturers, wholesalers and suppliers', 9),
    ('packaging-materials', 'Thermocol Packaging', 'packaging-materials-thermocol-packaging', 'Bulk Thermocol Packaging manufacturers, wholesalers and suppliers', 10),
    ('automobile-parts', 'Engine Parts', 'automobile-parts-engine-parts', 'Bulk Engine Parts manufacturers, wholesalers and suppliers', 1),
    ('automobile-parts', 'Brake Parts', 'automobile-parts-brake-parts', 'Bulk Brake Parts manufacturers, wholesalers and suppliers', 2),
    ('automobile-parts', 'Tyres', 'automobile-parts-tyres', 'Bulk Tyres manufacturers, wholesalers and suppliers', 3),
    ('automobile-parts', 'Batteries', 'automobile-parts-batteries', 'Bulk Batteries manufacturers, wholesalers and suppliers', 4),
    ('automobile-parts', 'Lubricants', 'automobile-parts-lubricants', 'Bulk Lubricants manufacturers, wholesalers and suppliers', 5),
    ('automobile-parts', 'Auto Electricals', 'automobile-parts-auto-electricals', 'Bulk Auto Electricals manufacturers, wholesalers and suppliers', 6),
    ('automobile-parts', 'Tractor Parts', 'automobile-parts-tractor-parts', 'Bulk Tractor Parts manufacturers, wholesalers and suppliers', 7),
    ('automobile-parts', 'Two Wheeler Parts', 'automobile-parts-two-wheeler-parts', 'Bulk Two Wheeler Parts manufacturers, wholesalers and suppliers', 8),
    ('automobile-parts', 'Truck Parts', 'automobile-parts-truck-parts', 'Bulk Truck Parts manufacturers, wholesalers and suppliers', 9),
    ('automobile-parts', 'Car Accessories', 'automobile-parts-car-accessories', 'Bulk Car Accessories manufacturers, wholesalers and suppliers', 10),
    ('medical-healthcare', 'Medical Equipment', 'medical-healthcare-medical-equipment', 'Bulk Medical Equipment manufacturers, wholesalers and suppliers', 1),
    ('medical-healthcare', 'Hospital Furniture', 'medical-healthcare-hospital-furniture', 'Bulk Hospital Furniture manufacturers, wholesalers and suppliers', 2),
    ('medical-healthcare', 'Surgical Instruments', 'medical-healthcare-surgical-instruments', 'Bulk Surgical Instruments manufacturers, wholesalers and suppliers', 3),
    ('medical-healthcare', 'Disposables', 'medical-healthcare-disposables', 'Bulk Disposables manufacturers, wholesalers and suppliers', 4),
    ('medical-healthcare', 'Diagnostic Equipment', 'medical-healthcare-diagnostic-equipment', 'Bulk Diagnostic Equipment manufacturers, wholesalers and suppliers', 5),
    ('medical-healthcare', 'Personal Protective Equipment', 'medical-healthcare-personal-protective-equipment', 'Bulk Personal Protective Equipment manufacturers, wholesalers and suppliers', 6),
    ('medical-healthcare', 'Pharmaceuticals', 'medical-healthcare-pharmaceuticals', 'Bulk Pharmaceuticals manufacturers, wholesalers and suppliers', 7),
    ('medical-healthcare', 'Ayurvedic Products', 'medical-healthcare-ayurvedic-products', 'Bulk Ayurvedic Products manufacturers, wholesalers and suppliers', 8),
    ('medical-healthcare', 'Dental Supplies', 'medical-healthcare-dental-supplies', 'Bulk Dental Supplies manufacturers, wholesalers and suppliers', 9),
    ('medical-healthcare', 'Rehabilitation Aids', 'medical-healthcare-rehabilitation-aids', 'Bulk Rehabilitation Aids manufacturers, wholesalers and suppliers', 10),
    ('metals-alloys', 'Steel', 'metals-alloys-steel', 'Bulk Steel manufacturers, wholesalers and suppliers', 1),
    ('metals-alloys', 'Aluminium', 'metals-alloys-aluminium', 'Bulk Aluminium manufacturers, wholesalers and suppliers', 2),
    ('metals-alloys', 'Copper', 'metals-alloys-copper', 'Bulk Copper manufacturers, wholesalers and suppliers', 3),
    ('metals-alloys', 'Brass', 'metals-alloys-brass', 'Bulk Brass manufacturers, wholesalers and suppliers', 4),
    ('metals-alloys', 'Stainless Steel', 'metals-alloys-stainless-steel', 'Bulk Stainless Steel manufacturers, wholesalers and suppliers', 5),
    ('metals-alloys', 'MS Plates', 'metals-alloys-ms-plates', 'Bulk MS Plates manufacturers, wholesalers and suppliers', 6),
    ('metals-alloys', 'GI Sheets', 'metals-alloys-gi-sheets', 'Bulk GI Sheets manufacturers, wholesalers and suppliers', 7),
    ('metals-alloys', 'Metal Scrap', 'metals-alloys-metal-scrap', 'Bulk Metal Scrap manufacturers, wholesalers and suppliers', 8),
    ('metals-alloys', 'Fasteners', 'metals-alloys-fasteners', 'Bulk Fasteners manufacturers, wholesalers and suppliers', 9),
    ('metals-alloys', 'Casting Products', 'metals-alloys-casting-products', 'Bulk Casting Products manufacturers, wholesalers and suppliers', 10),
    ('plastic-rubber-products', 'Plastic Raw Materials', 'plastic-rubber-products-plastic-raw-materials', 'Bulk Plastic Raw Materials manufacturers, wholesalers and suppliers', 1),
    ('plastic-rubber-products', 'Rubber Sheets', 'plastic-rubber-products-rubber-sheets', 'Bulk Rubber Sheets manufacturers, wholesalers and suppliers', 2),
    ('plastic-rubber-products', 'Moulded Plastic Parts', 'plastic-rubber-products-moulded-plastic-parts', 'Bulk Moulded Plastic Parts manufacturers, wholesalers and suppliers', 3),
    ('plastic-rubber-products', 'PVC Products', 'plastic-rubber-products-pvc-products', 'Bulk PVC Products manufacturers, wholesalers and suppliers', 4),
    ('plastic-rubber-products', 'HDPE Products', 'plastic-rubber-products-hdpe-products', 'Bulk HDPE Products manufacturers, wholesalers and suppliers', 5),
    ('plastic-rubber-products', 'Rubber Hoses', 'plastic-rubber-products-rubber-hoses', 'Bulk Rubber Hoses manufacturers, wholesalers and suppliers', 6),
    ('plastic-rubber-products', 'Plastic Containers', 'plastic-rubber-products-plastic-containers', 'Bulk Plastic Containers manufacturers, wholesalers and suppliers', 7),
    ('plastic-rubber-products', 'Industrial Rubber', 'plastic-rubber-products-industrial-rubber', 'Bulk Industrial Rubber manufacturers, wholesalers and suppliers', 8),
    ('plastic-rubber-products', 'Acrylic Sheets', 'plastic-rubber-products-acrylic-sheets', 'Bulk Acrylic Sheets manufacturers, wholesalers and suppliers', 9),
    ('plastic-rubber-products', 'Plastic Granules', 'plastic-rubber-products-plastic-granules', 'Bulk Plastic Granules manufacturers, wholesalers and suppliers', 10),
    ('office-school-supplies', 'Office Furniture', 'office-school-supplies-office-furniture', 'Bulk Office Furniture manufacturers, wholesalers and suppliers', 1),
    ('office-school-supplies', 'Stationery', 'office-school-supplies-stationery', 'Bulk Stationery manufacturers, wholesalers and suppliers', 2),
    ('office-school-supplies', 'Printers', 'office-school-supplies-printers', 'Bulk Printers manufacturers, wholesalers and suppliers', 3),
    ('office-school-supplies', 'School Furniture', 'office-school-supplies-school-furniture', 'Bulk School Furniture manufacturers, wholesalers and suppliers', 4),
    ('office-school-supplies', 'Files & Folders', 'office-school-supplies-files-folders', 'Bulk Files & Folders manufacturers, wholesalers and suppliers', 5),
    ('office-school-supplies', 'Writing Instruments', 'office-school-supplies-writing-instruments', 'Bulk Writing Instruments manufacturers, wholesalers and suppliers', 6),
    ('office-school-supplies', 'Corporate Gifts', 'office-school-supplies-corporate-gifts', 'Bulk Corporate Gifts manufacturers, wholesalers and suppliers', 7),
    ('office-school-supplies', 'Whiteboards', 'office-school-supplies-whiteboards', 'Bulk Whiteboards manufacturers, wholesalers and suppliers', 8),
    ('office-school-supplies', 'Paper Products', 'office-school-supplies-paper-products', 'Bulk Paper Products manufacturers, wholesalers and suppliers', 9),
    ('office-school-supplies', 'Office Automation', 'office-school-supplies-office-automation', 'Bulk Office Automation manufacturers, wholesalers and suppliers', 10),
    ('furniture-home-decor', 'Modular Furniture', 'furniture-home-decor-modular-furniture', 'Bulk Modular Furniture manufacturers, wholesalers and suppliers', 1),
    ('furniture-home-decor', 'Office Chairs', 'furniture-home-decor-office-chairs', 'Bulk Office Chairs manufacturers, wholesalers and suppliers', 2),
    ('furniture-home-decor', 'Wooden Furniture', 'furniture-home-decor-wooden-furniture', 'Bulk Wooden Furniture manufacturers, wholesalers and suppliers', 3),
    ('furniture-home-decor', 'Metal Furniture', 'furniture-home-decor-metal-furniture', 'Bulk Metal Furniture manufacturers, wholesalers and suppliers', 4),
    ('furniture-home-decor', 'Mattresses', 'furniture-home-decor-mattresses', 'Bulk Mattresses manufacturers, wholesalers and suppliers', 5),
    ('furniture-home-decor', 'Lighting Decor', 'furniture-home-decor-lighting-decor', 'Bulk Lighting Decor manufacturers, wholesalers and suppliers', 6),
    ('furniture-home-decor', 'Curtains', 'furniture-home-decor-curtains', 'Bulk Curtains manufacturers, wholesalers and suppliers', 7),
    ('furniture-home-decor', 'Wall Decor', 'furniture-home-decor-wall-decor', 'Bulk Wall Decor manufacturers, wholesalers and suppliers', 8),
    ('furniture-home-decor', 'Kitchen Furniture', 'furniture-home-decor-kitchen-furniture', 'Bulk Kitchen Furniture manufacturers, wholesalers and suppliers', 9),
    ('furniture-home-decor', 'Outdoor Furniture', 'furniture-home-decor-outdoor-furniture', 'Bulk Outdoor Furniture manufacturers, wholesalers and suppliers', 10),
    ('safety-security', 'Fire Safety', 'safety-security-fire-safety', 'Bulk Fire Safety manufacturers, wholesalers and suppliers', 1),
    ('safety-security', 'Safety Shoes', 'safety-security-safety-shoes', 'Bulk Safety Shoes manufacturers, wholesalers and suppliers', 2),
    ('safety-security', 'Helmets', 'safety-security-helmets', 'Bulk Helmets manufacturers, wholesalers and suppliers', 3),
    ('safety-security', 'Security Systems', 'safety-security-security-systems', 'Bulk Security Systems manufacturers, wholesalers and suppliers', 4),
    ('safety-security', 'Access Control', 'safety-security-access-control', 'Bulk Access Control manufacturers, wholesalers and suppliers', 5),
    ('safety-security', 'Safety Gloves', 'safety-security-safety-gloves', 'Bulk Safety Gloves manufacturers, wholesalers and suppliers', 6),
    ('safety-security', 'Reflective Jackets', 'safety-security-reflective-jackets', 'Bulk Reflective Jackets manufacturers, wholesalers and suppliers', 7),
    ('safety-security', 'CCTV', 'safety-security-cctv', 'Bulk CCTV manufacturers, wholesalers and suppliers', 8),
    ('safety-security', 'First Aid', 'safety-security-first-aid', 'Bulk First Aid manufacturers, wholesalers and suppliers', 9),
    ('safety-security', 'Road Safety', 'safety-security-road-safety', 'Bulk Road Safety manufacturers, wholesalers and suppliers', 10),
    ('logistics-material-handling', 'Forklifts', 'logistics-material-handling-forklifts', 'Bulk Forklifts manufacturers, wholesalers and suppliers', 1),
    ('logistics-material-handling', 'Conveyors', 'logistics-material-handling-conveyors', 'Bulk Conveyors manufacturers, wholesalers and suppliers', 2),
    ('logistics-material-handling', 'Trolleys', 'logistics-material-handling-trolleys', 'Bulk Trolleys manufacturers, wholesalers and suppliers', 3),
    ('logistics-material-handling', 'Cranes', 'logistics-material-handling-cranes', 'Bulk Cranes manufacturers, wholesalers and suppliers', 4),
    ('logistics-material-handling', 'Warehouse Racks', 'logistics-material-handling-warehouse-racks', 'Bulk Warehouse Racks manufacturers, wholesalers and suppliers', 5),
    ('logistics-material-handling', 'Material Lifts', 'logistics-material-handling-material-lifts', 'Bulk Material Lifts manufacturers, wholesalers and suppliers', 6),
    ('logistics-material-handling', 'Pallet Trucks', 'logistics-material-handling-pallet-trucks', 'Bulk Pallet Trucks manufacturers, wholesalers and suppliers', 7),
    ('logistics-material-handling', 'Weighing Scales', 'logistics-material-handling-weighing-scales', 'Bulk Weighing Scales manufacturers, wholesalers and suppliers', 8),
    ('logistics-material-handling', 'Storage Bins', 'logistics-material-handling-storage-bins', 'Bulk Storage Bins manufacturers, wholesalers and suppliers', 9),
    ('logistics-material-handling', 'Dock Equipment', 'logistics-material-handling-dock-equipment', 'Bulk Dock Equipment manufacturers, wholesalers and suppliers', 10),
    ('it-software-services', 'ERP Software', 'it-software-services-erp-software', 'Bulk ERP Software manufacturers, wholesalers and suppliers', 1),
    ('it-software-services', 'CRM Software', 'it-software-services-crm-software', 'Bulk CRM Software manufacturers, wholesalers and suppliers', 2),
    ('it-software-services', 'Website Development', 'it-software-services-website-development', 'Bulk Website Development manufacturers, wholesalers and suppliers', 3),
    ('it-software-services', 'Mobile App Development', 'it-software-services-mobile-app-development', 'Bulk Mobile App Development manufacturers, wholesalers and suppliers', 4),
    ('it-software-services', 'Cloud Services', 'it-software-services-cloud-services', 'Bulk Cloud Services manufacturers, wholesalers and suppliers', 5),
    ('it-software-services', 'Cyber Security', 'it-software-services-cyber-security', 'Bulk Cyber Security manufacturers, wholesalers and suppliers', 6),
    ('it-software-services', 'POS Software', 'it-software-services-pos-software', 'Bulk POS Software manufacturers, wholesalers and suppliers', 7),
    ('it-software-services', 'Accounting Software', 'it-software-services-accounting-software', 'Bulk Accounting Software manufacturers, wholesalers and suppliers', 8),
    ('it-software-services', 'Digital Marketing', 'it-software-services-digital-marketing', 'Bulk Digital Marketing manufacturers, wholesalers and suppliers', 9),
    ('it-software-services', 'IT Hardware', 'it-software-services-it-hardware', 'Bulk IT Hardware manufacturers, wholesalers and suppliers', 10),
    ('printing-advertising', 'Offset Printing', 'printing-advertising-offset-printing', 'Bulk Offset Printing manufacturers, wholesalers and suppliers', 1),
    ('printing-advertising', 'Digital Printing', 'printing-advertising-digital-printing', 'Bulk Digital Printing manufacturers, wholesalers and suppliers', 2),
    ('printing-advertising', 'Sign Boards', 'printing-advertising-sign-boards', 'Bulk Sign Boards manufacturers, wholesalers and suppliers', 3),
    ('printing-advertising', 'Banners', 'printing-advertising-banners', 'Bulk Banners manufacturers, wholesalers and suppliers', 4),
    ('printing-advertising', 'Promotional Gifts', 'printing-advertising-promotional-gifts', 'Bulk Promotional Gifts manufacturers, wholesalers and suppliers', 5),
    ('printing-advertising', 'Packaging Printing', 'printing-advertising-packaging-printing', 'Bulk Packaging Printing manufacturers, wholesalers and suppliers', 6),
    ('printing-advertising', 'Flex Printing', 'printing-advertising-flex-printing', 'Bulk Flex Printing manufacturers, wholesalers and suppliers', 7),
    ('printing-advertising', 'Business Cards', 'printing-advertising-business-cards', 'Bulk Business Cards manufacturers, wholesalers and suppliers', 8),
    ('printing-advertising', 'Brochures', 'printing-advertising-brochures', 'Bulk Brochures manufacturers, wholesalers and suppliers', 9),
    ('printing-advertising', 'Outdoor Advertising', 'printing-advertising-outdoor-advertising', 'Bulk Outdoor Advertising manufacturers, wholesalers and suppliers', 10)
)
INSERT INTO public.categories (name, slug, description, parent_id, level, is_active, display_order, sort_order)
SELECT cs.name, cs.slug, cs.description, p.id, 2, true, cs.display_order, cs.display_order
FROM child_seed cs
JOIN public.categories p ON p.slug = cs.parent_slug
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = COALESCE(public.categories.description, EXCLUDED.description),
  parent_id = EXCLUDED.parent_id,
  level = 2,
  is_active = true,
  display_order = EXCLUDED.display_order,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();

-- Keep public buyer requirements gated to admin assignment
UPDATE public.requirements SET is_public = false WHERE status IN ('pending_admin','assigned') OR status IS NULL;
DROP POLICY IF EXISTS "Public reqs visible" ON public.requirements;
DROP POLICY IF EXISTS "Approved sellers can view open requirements" ON public.requirements;
DROP POLICY IF EXISTS "Anyone can read requirement attachments" ON storage.objects;
CREATE POLICY "Anyone can read requirement attachments" ON storage.objects FOR SELECT TO public USING (bucket_id = 'requirement-attachments');
