// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjtxyoaqtxsfbtrzsimb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqdHh5b2FxdHhzZmJ0cnpzaW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI2NTQyMjQsImV4cCI6MjA5ODIzMDIyNH0.CRPd9F-RIWjGvtx36So7nAYNfA_OFnnHRi41oGheXcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});